import { createProvider, type OAuthProvider } from "../oauth/providers";
import { validateOAuthRedirectUri } from "../oauth/redirect-uri";
import type { EncryptedEnvelope, OAuthProviderId, UserRow } from "../types";
import { loadWorkerConfig, type WorkerConfig, type WorkerEnv } from "./config";

const cors = { "Access-Control-Allow-Methods": "GET, POST, PUT, PATCH, DELETE, OPTIONS", "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Admin-Token", Vary: "Origin" };
class HttpError extends Error { constructor(readonly status: number, readonly payload: Record<string, unknown>) { super(String(payload.message)); } }
const fail = (status: number, message: string, extra: Record<string, unknown> = {}) => new HttpError(status, { success: false, message, ...extra });
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json; charset=UTF-8" } });
const nocontent = () => new Response(null, { status: 204, headers: cors });
const now = () => new Date().toISOString();
const day = () => `${now().slice(0, 10)}T00:00:00.000Z`;
function token(bytes = 32) { const values = crypto.getRandomValues(new Uint8Array(bytes)); let text = ""; for (const value of values) text += String.fromCharCode(value); return btoa(text).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, ""); }
async function digest(text: string) { const values = new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text))); return [...values].map((value) => value.toString(16).padStart(2, "0")).join(""); }
async function sameSecret(left: string | null, right: string): Promise<boolean> { const a = new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(left ?? ""))); const b = new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(right))); let difference = 0; for (let index = 0; index < a.length; index += 1) difference |= a[index]! ^ b[index]!; return difference === 0; }
async function pkce() { const verifier = token(48); const values = new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(verifier))); let text = ""; for (const value of values) text += String.fromCharCode(value); return { verifier, challenge: btoa(text).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "") }; }
function providerId(value: string): OAuthProviderId { if (value === "github" || value === "google" || value === "linuxdo") return value; throw fail(404, "OAuth provider not found"); }
function bucketId(value: unknown) { if (typeof value !== "string" || !/^[A-Za-z0-9]{1,64}$/.test(value)) throw fail(400, "Invalid ID. Only letters and numbers are allowed."); return value; }
function bytes(value: string) { const padding = "=".repeat((4 - value.length % 4) % 4); return atob(value.replace(/-/g, "+").replace(/_/g, "/") + padding).length; }
function encrypted(value: unknown): EncryptedEnvelope { const x = value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : undefined; if (!x || x.version !== 1 || typeof x.salt !== "string" || typeof x.iv !== "string" || typeof x.payload !== "string" || !/^[A-Za-z0-9_-]+$/.test(x.salt) || !/^[A-Za-z0-9_-]+$/.test(x.iv) || !/^[A-Za-z0-9_-]+$/.test(x.payload)) throw fail(400, "Invalid encrypted payload"); try { if (bytes(x.salt) !== 16 || bytes(x.iv) !== 12 || bytes(x.payload) < 16) throw fail(400, "Invalid encrypted payload"); } catch { throw fail(400, "Invalid encrypted payload"); } return x as unknown as EncryptedEnvelope; }
async function payload(request: Request) { try { const x: unknown = await request.json(); if (!x || typeof x !== "object" || Array.isArray(x)) throw fail(400, "Invalid payload"); return x as Record<string, unknown>; } catch (cause) { if (cause instanceof HttpError) throw cause; throw fail(400, "Invalid JSON payload"); } }
function redirect(uri: string, args: Record<string, string>) { const target = new URL(uri); Object.entries(args).forEach(([k, v]) => target.searchParams.set(k, v)); return new Response(null, { status: 302, headers: { ...cors, Location: target.toString() } }); }
async function first<T>(db: D1Database, sql: string, ...args: unknown[]) { return (await db.prepare(sql).bind(...args).first<T>()) ?? undefined; }
async function rows<T>(db: D1Database, sql: string, ...args: unknown[]) { return (await db.prepare(sql).bind(...args).all<T>()).results; }
function toUser(row: UserRow) { return { id: Number(row.id), displayName: row.display_name, quotaBytes: Number(row.quota_bytes), dailyRequestLimit: Number(row.daily_request_limit), created_at: row.created_at, updated_at: row.updated_at }; }
function oauth(config: WorkerConfig) { return new Map<OAuthProviderId, OAuthProvider>(config.oauthProviders.map((spec) => { const provider = createProvider(spec); return [provider.id, provider]; })); }
async function session(request: Request, db: D1Database) { const header = request.headers.get("Authorization"); if (!header?.startsWith("Bearer ")) throw fail(401, "Unauthorized"); const hash = await digest(header.slice(7)); const row = await first<{ user_id: number; expires_at: string }>(db, "SELECT user_id, expires_at FROM sessions WHERE token_hash = ?", hash); if (!row || row.expires_at <= now()) { if (row) await db.prepare("DELETE FROM sessions WHERE token_hash = ?").bind(hash).run(); throw fail(401, "Session expired or invalid"); } return Number(row.user_id); }
async function throttle(request: Request, db: D1Database, config: WorkerConfig, scope = "login") { const ip = request.headers.get("CF-Connecting-IP") ?? request.headers.get("X-Forwarded-For")?.split(",")[0]?.trim() ?? "unknown"; const key = `${scope}:${ip}`; const cutoff = new Date(Date.now() - config.loginRateWindowMin * 60000).toISOString(); const count = await first<{ count: number }>(db, "SELECT COUNT(*) AS count FROM login_attempts WHERE ip = ? AND attempted_at > ?", key, cutoff); if (Number(count?.count ?? 0) >= config.loginRateLimit) throw fail(429, "Too many attempts. Try again later."); await db.prepare("INSERT INTO login_attempts (ip, attempted_at) VALUES (?, ?)").bind(key, now()).run(); }
async function limited(request: Request, db: D1Database, userId: number) { const user = await first<UserRow>(db, "SELECT * FROM users WHERE id = ?", userId); if (!user) throw fail(401, "User not found"); const count = await first<{ count: number }>(db, "SELECT COUNT(*) AS count FROM request_log WHERE user_id = ? AND created_at >= ?", userId, day()); if (Number(count?.count ?? 0) >= Number(user.daily_request_limit)) throw fail(429, "Daily request limit reached"); await db.prepare("INSERT INTO request_log (user_id, bucket_id, endpoint, created_at) VALUES (?, NULL, ?, ?)").bind(userId, `${request.method} ${new URL(request.url).pathname}`, now()).run(); return user; }
async function authUser(db: D1Database, user: UserRow) { const providers = await rows<{ provider: OAuthProviderId; login: string }>(db, "SELECT provider, login FROM provider_accounts WHERE user_id = ? ORDER BY id ASC", user.id); return { ...toUser(user), providers: providers.map(({ provider, login }) => ({ id: provider, login })) }; }

async function route(request: Request, env: WorkerEnv): Promise<Response> {
  if (request.method === "OPTIONS") return nocontent();
  const path = new URL(request.url).pathname;
  if (!path.startsWith("/api/v1/")) return env.ASSETS.fetch(request);
  if (request.method === "GET" && path === "/api/v1/health") return json({ status: "ok", version: 1 });
  const config = loadWorkerConfig(env), configured = oauth(config);
  if (request.method === "GET" && path === "/api/v1/auth/providers") return json({ providers: [...configured.values()].map(({ id, name }) => ({ id, name })) });
  const match = path.match(/^\/api\/v1\/auth\/oauth\/(github|google|linuxdo)\/(start|callback)$/);
  if (match?.[2] === "start" && request.method === "POST") {
    await throttle(request, env.DB, config); const provider = configured.get(providerId(match[1]!)); if (!provider) throw fail(404, "OAuth provider is not configured"); const data = await payload(request); const mode = data.mode === "login" || data.mode === "link" ? data.mode : undefined; if (!mode) throw fail(400, "Invalid OAuth mode"); let userId: number | null = null; if (mode === "link") userId = await session(request, env.DB); const target = validateOAuthRedirectUri(data.redirectUri, config.allowedExtensionIds, config.publicBaseUrl); const proof = await pkce(), state = token(), created = now(); await env.DB.prepare("INSERT INTO oauth_states (state, provider, mode, user_id, redirect_uri, code_verifier, created_at, expires_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").bind(state, provider.id, mode, userId, target, proof.verifier, created, new Date(Date.now() + 600000).toISOString()).run(); return json({ authorizeUrl: provider.authorizeUrl({ redirectUri: `${config.publicBaseUrl}/api/v1/auth/oauth/${provider.id}/callback`, state, codeChallenge: proof.challenge }) });
  }
  if (match?.[2] === "callback" && request.method === "GET") {
    await throttle(request, env.DB, config); const key = providerId(match[1]!), url = new URL(request.url); const state = await first<{ provider: OAuthProviderId; mode: "login" | "link"; user_id: number | null; redirect_uri: string; code_verifier: string }>(env.DB, "DELETE FROM oauth_states WHERE state = ? AND expires_at > ? RETURNING provider, mode, user_id, redirect_uri, code_verifier", url.searchParams.get("state") ?? "", now()); if (!state || state.provider !== key) throw fail(400, "Invalid or expired OAuth state"); if (url.searchParams.has("error")) return redirect(state.redirect_uri, { error: "provider_denied" }); const code = url.searchParams.get("code"); if (!code) return redirect(state.redirect_uri, { error: "missing_code" }); const provider = configured.get(key); if (!provider) throw fail(404, "OAuth provider is not configured"); let identity; try { identity = await provider.exchangeCode({ code, redirectUri: `${config.publicBaseUrl}/api/v1/auth/oauth/${key}/callback`, codeVerifier: state.code_verifier }); } catch { return redirect(state.redirect_uri, { error: "provider_exchange_failed" }); }
    if (state.mode === "link") { const linked = await first<{ user_id: number }>(env.DB, "SELECT user_id FROM provider_accounts WHERE provider = ? AND subject = ?", key, identity.subject); if (linked && Number(linked.user_id) !== state.user_id) return redirect(state.redirect_uri, { error: "provider_already_linked" }); if (!linked) await env.DB.prepare("INSERT INTO provider_accounts (user_id, provider, subject, login, created_at) VALUES (?, ?, ?, ?, ?)").bind(state.user_id, key, identity.subject, identity.login, now()).run(); return redirect(state.redirect_uri, { linked: "1" }); }
    let account = await first<{ user_id: number }>(env.DB, "SELECT user_id FROM provider_accounts WHERE provider = ? AND subject = ?", key, identity.subject); let userId: number; if (account) userId = Number(account.user_id); else { const created = await env.DB.prepare("INSERT INTO users (display_name, quota_bytes, daily_request_limit, created_at, updated_at) VALUES (?, ?, ?, ?, ?) RETURNING id").bind(identity.login, config.defaultQuotaBytes, config.defaultDailyRequestLimit, now(), now()).first<{ id: number }>(); userId = Number(created?.id); await env.DB.prepare("INSERT INTO provider_accounts (user_id, provider, subject, login, created_at) VALUES (?, ?, ?, ?, ?)").bind(userId, key, identity.subject, identity.login, now()).run(); } const exchange = token(); await env.DB.prepare("INSERT INTO oauth_exchange_codes (code_hash, user_id, created_at, expires_at) VALUES (?, ?, ?, ?)").bind(await digest(exchange), userId, now(), new Date(Date.now() + 120000).toISOString()).run(); return redirect(state.redirect_uri, { code: exchange });
  }
  if (request.method === "POST" && path === "/api/v1/auth/oauth/exchange") { await throttle(request, env.DB, config); const code = (await payload(request)).code; if (typeof code !== "string" || !code) throw fail(400, "Invalid exchange code"); const exchange = await first<{ user_id: number }>(env.DB, "DELETE FROM oauth_exchange_codes WHERE code_hash = ? AND expires_at > ? RETURNING user_id", await digest(code), now()); if (!exchange) throw fail(401, "Invalid or expired exchange code"); const user = await first<UserRow>(env.DB, "SELECT * FROM users WHERE id = ?", exchange.user_id); if (!user) throw fail(401, "User not found"); const raw = token(); await env.DB.prepare("INSERT INTO sessions (token_hash, user_id, created_at, expires_at) VALUES (?, ?, ?, ?)").bind(await digest(raw), user.id, now(), new Date(Date.now() + config.sessionTtlHours * 3600000).toISOString()).run(); return json({ token: raw, user: await authUser(env.DB, user) }); }
  const unlink = path.match(/^\/api\/v1\/auth\/oauth\/(github|google|linuxdo)$/);
  if (request.method === "DELETE" && unlink) { const userId = await session(request, env.DB), accounts = await rows<{ provider: OAuthProviderId; login: string }>(env.DB, "SELECT provider, login FROM provider_accounts WHERE user_id = ? ORDER BY id ASC", userId); if (accounts.length < 2) throw fail(409, "Cannot unlink the last sign-in provider"); const result = await env.DB.prepare("DELETE FROM provider_accounts WHERE user_id = ? AND provider = ?").bind(userId, providerId(unlink[1]!)).run(); if (!result.meta.changes) throw fail(404, "Provider is not linked"); return json({ providers: accounts.filter((x) => x.provider !== unlink[1]).map(({ provider, login }) => ({ id: provider, login })) }); }
  if (request.method === "POST" && path === "/api/v1/auth/logout") { await session(request, env.DB); await env.DB.prepare("DELETE FROM sessions WHERE token_hash = ?").bind(await digest(request.headers.get("Authorization")!.slice(7))).run(); return nocontent(); }
  if (request.method === "GET" && path === "/api/v1/me") { const user = await limited(request, env.DB, await session(request, env.DB)); const used = await first<{ total: number }>(env.DB, "SELECT COALESCE(SUM(payload_bytes), 0) AS total FROM buckets WHERE user_id = ?", user.id); const count = await first<{ count: number }>(env.DB, "SELECT COUNT(*) AS count FROM request_log WHERE user_id = ? AND created_at >= ?", user.id, day()); return json({ user: await authUser(env.DB, user), usage: { usedBytes: Number(used?.total ?? 0), todayRequests: Number(count?.count ?? 0), todayRequestsLimit: Number(user.daily_request_limit) } }); }
  return await buckets(request, env, path);
}

async function buckets(request: Request, env: WorkerEnv, path: string): Promise<Response> {
  const config = loadWorkerConfig(env);
  if (path === "/api/v1/buckets" && (request.method === "GET" || request.method === "POST")) {
    const userId = await session(request, env.DB), user = await limited(request, env.DB, userId);
    if (request.method === "GET") { const list = await rows<{ id: string; payload_bytes: number; created_at: string; updated_at: string }>(env.DB, "SELECT id, payload_bytes, created_at, updated_at FROM buckets WHERE user_id = ? ORDER BY updated_at DESC", userId); return json({ buckets: list.map((item) => ({ id: item.id, size: Number(item.payload_bytes), createdAt: item.created_at, updatedAt: item.updated_at })) }); }
    const data = await payload(request), id = bucketId(data.id), value = encrypted(data.envelope); const exists = await first(env.DB, "SELECT 1 FROM buckets WHERE user_id = ? AND id = ?", userId, id); if (exists) throw fail(409, "Bucket already exists"); const total = await first<{ total: number }>(env.DB, "SELECT COALESCE(SUM(payload_bytes), 0) AS total FROM buckets WHERE user_id = ?", userId); const size = bytes(value.payload); if (Number(total?.total ?? 0) + size > Number(user.quota_bytes)) throw fail(413, "Storage quota exceeded", { quotaBytes: Number(user.quota_bytes), usedBytes: Number(total?.total ?? 0) }); const created = now(); await env.DB.prepare("INSERT INTO buckets (id, user_id, envelope_json, payload_bytes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)").bind(id, userId, JSON.stringify(value), size, created, created).run(); return json({ id, size, createdAt: created, updatedAt: created }, 201);
  }
  const match = path.match(/^\/api\/v1\/buckets\/([^/]+)$/);
  if (match && ["GET", "PUT", "DELETE"].includes(request.method)) {
    const userId = await session(request, env.DB), user = await limited(request, env.DB, userId), id = bucketId(decodeURIComponent(match[1]!)); const existing = await first<{ envelope_json: string; payload_bytes: number; created_at: string; updated_at: string }>(env.DB, "SELECT envelope_json, payload_bytes, created_at, updated_at FROM buckets WHERE user_id = ? AND id = ?", userId, id); if (!existing) throw fail(404, "Bucket not found"); if (request.method === "GET") return json({ id, size: Number(existing.payload_bytes), createdAt: existing.created_at, updatedAt: existing.updated_at, envelope: JSON.parse(existing.envelope_json) }); if (request.method === "DELETE") { await env.DB.prepare("DELETE FROM buckets WHERE user_id = ? AND id = ?").bind(userId, id).run(); return nocontent(); }
    const value = encrypted((await payload(request)).envelope), size = bytes(value.payload), total = await first<{ total: number }>(env.DB, "SELECT COALESCE(SUM(payload_bytes), 0) AS total FROM buckets WHERE user_id = ?", userId); if (Number(total?.total ?? 0) - Number(existing.payload_bytes) + size > Number(user.quota_bytes)) throw fail(413, "Storage quota exceeded", { quotaBytes: Number(user.quota_bytes), usedBytes: Number(total?.total ?? 0) }); const updated = now(); await env.DB.prepare("UPDATE buckets SET envelope_json = ?, payload_bytes = ?, updated_at = ? WHERE user_id = ? AND id = ?").bind(JSON.stringify(value), size, updated, userId, id).run(); return json({ id, size, createdAt: updated, updatedAt: updated });
  }
  if (path === "/api/v1/admin/users" && request.method === "GET") { await throttle(request, env.DB, config, "admin"); if (!(await sameSecret(request.headers.get("X-Admin-Token"), config.adminToken))) throw fail(401, "Unauthorized"); const users = await rows<UserRow>(env.DB, "SELECT * FROM users ORDER BY id ASC"); return json({ users: await Promise.all(users.map(async (user) => { const used = await first<{ total: number }>(env.DB, "SELECT COALESCE(SUM(payload_bytes), 0) AS total FROM buckets WHERE user_id = ?", user.id); return { id: Number(user.id), displayName: user.display_name, quotaBytes: Number(user.quota_bytes), dailyRequestLimit: Number(user.daily_request_limit), usedBytes: Number(used?.total ?? 0), createdAt: user.created_at, updatedAt: user.updated_at }; })) }); }
  const admin = path.match(/^\/api\/v1\/admin\/users\/(\d+)$/);
  if (admin && request.method === "PATCH") { await throttle(request, env.DB, config, "admin"); if (!(await sameSecret(request.headers.get("X-Admin-Token"), config.adminToken))) throw fail(401, "Unauthorized"); const id = Number(admin[1]); const data = await payload(request); const valid = (value: unknown) => typeof value === "number" && Number.isSafeInteger(value) && value >= 0; if ((data.quotaBytes !== undefined && !valid(data.quotaBytes)) || (data.dailyRequestLimit !== undefined && !valid(data.dailyRequestLimit))) throw fail(400, data.quotaBytes !== undefined && !valid(data.quotaBytes) ? "Invalid quotaBytes" : "Invalid dailyRequestLimit"); if (data.quotaBytes === undefined && data.dailyRequestLimit === undefined) throw fail(400, "No quota values provided"); const user = await first<UserRow>(env.DB, "SELECT * FROM users WHERE id = ?", id); if (!user) throw fail(404, "User not found"); const updated = now(), quota = data.quotaBytes ?? Number(user.quota_bytes), daily = data.dailyRequestLimit ?? Number(user.daily_request_limit); await env.DB.prepare("UPDATE users SET quota_bytes = ?, daily_request_limit = ?, updated_at = ? WHERE id = ?").bind(quota, daily, updated, id).run(); return json({ user: { id, displayName: user.display_name, quotaBytes: quota, dailyRequestLimit: daily, updatedAt: updated } }); }
  throw fail(404, "Not Found");
}

async function cleanup(env: WorkerEnv) { const config = loadWorkerConfig(env), current = now(), requests = new Date(Date.now() - config.requestLogRetentionDays * 86400000).toISOString(), logins = new Date(Date.now() - config.loginRateWindowMin * 60000).toISOString(); await env.DB.batch([env.DB.prepare("DELETE FROM sessions WHERE expires_at < ?").bind(current), env.DB.prepare("DELETE FROM oauth_states WHERE expires_at < ?").bind(current), env.DB.prepare("DELETE FROM oauth_exchange_codes WHERE expires_at < ?").bind(current), env.DB.prepare("DELETE FROM request_log WHERE created_at < ?").bind(requests), env.DB.prepare("DELETE FROM login_attempts WHERE attempted_at < ?").bind(logins)]); }
function secureResponse(response: Response, request: Request, env: WorkerEnv): Response { const headers = new Headers(response.headers); headers.set("Strict-Transport-Security", "max-age=63072000; includeSubDomains"); headers.set("Content-Security-Policy", "default-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'; object-src 'none'"); headers.set("X-Content-Type-Options", "nosniff"); headers.set("Referrer-Policy", "no-referrer"); const origin = request.headers.get("Origin"); const id = origin?.match(/^chrome-extension:\/\/([a-p]{32})$/)?.[1]; if (origin && id && loadWorkerConfig(env).allowedExtensionIds.includes(id)) headers.set("Access-Control-Allow-Origin", origin); return new Response(response.body, { status: response.status, statusText: response.statusText, headers }); }
export default { async fetch(request: Request, env: WorkerEnv) { try { return secureResponse(await route(request, env), request, env); } catch (cause) { if (cause instanceof HttpError) return secureResponse(json(cause.payload, cause.status), request, env); console.error("Unhandled Worker error", cause); return secureResponse(json({ success: false, message: "Internal Server Error" }, 500), request, env); } }, async scheduled(_controller: ScheduledController, env: WorkerEnv) { await cleanup(env); } } satisfies ExportedHandler<WorkerEnv>;
